### ISSUE TITLE
flink-faker 0.5.1 doesn't work with flink 1.14.4 due to api incompatability

### ISSUE THREAD

**Issue by zjffdu** [knaufk/flink-faker#99]
```
java.lang.AbstractMethodError: com.github.knaufk.flink.faker.FlinkFakerTableSource$1.produceDataStream(Lorg/apache/flink/streaming/api/environment/StreamExecutionEnvironment;)Lorg/apache/flink/streaming/api/datastream/DataStream;
	at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecTableSourceScan.translateToPlanInternal(CommonExecTableSourceScan.java:106)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:134)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecEdge.translateToPlan(ExecEdge.java:250)
	at org.apache.flink.table.planner.plan.nodes.exec.common.CommonExecCalc.translateToPlanInternal(CommonExecCalc.java:88)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:134)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecEdge.translateToPlan(ExecEdge.java:250)
	at org.apache.flink.table.planner.plan.nodes.exec.stream.StreamExecSink.translateToPlanInternal(StreamExecSink.java:114)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNodeBase.translateToPlan(ExecNodeBase.java:134)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$1.apply(StreamPlanner.scala:71)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$1.apply(StreamPlanner.scala:70)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
```

**Comment by knaufk** [comment]
Please see the compatibility matrix in the README. flink-faker 0.5.1 requires Flink 1.15.

**Comment by zjffdu** [comment]
Thanks @knaufk for the clarify, close it.
